openapi: 3.0.3
info:
  title: TurnosYa API
  version: '1.0.0'
  description: |
    La aplicación TurnosYa permite a sus usuarios reservar y cancelar turnos con sus doctores de preferencia.

    ### Algunas de sus funciones son:
    
    * Registro y autenticación de usuarios.
    * Gestión de perfil y obra social.
    * Consulta de disponibilidad de turnos.
    * Reserva, cancelación y visualización de turnos.
    * Notificaciones y recordatorios.
    * Gestión de médicos y especialidades.
    * Acceso a historial de turnos y notas médicas.
    * Visualización de resultados de estudios.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: http://localhost:8080
    description: Servidor local para desarrollo
security:
  - bearerAuth: []
paths:
  /user/register:
    post:
      summary: Registrar un nuevo usuario
      operationId: registrarUsuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '201':
          description: Usuario registrado exitosamente.
  /usuarios/login:
    post:
      summary: Iniciar sesión
      operationId: loginUsuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Inicio de sesión exitoso.
  /user/profile:
    get:
      summary: Obtener perfil del usuario
      operationId: obtenerPerfil
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Datos del perfil del usuario.
    put:
      summary: Editar perfil del usuario (excepto correo electrónico)
      operationId: editarPerfil
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
      responses:
        '200':
          description: Perfil actualizado correctamente.
  /user/insurance:
    put:
      summary: Cargar información de obra social
      operationId: cargarObraSocial
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insurance'
      responses:
        '200':
          description: Obra social registrada.
  /user/medical-history:
    get:
      summary: Obtener historial de turnos
      operationId: obtenerHistorialTurnos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Historial de turnos.
  /user/logout:
    post:
      summary: Cerrar sesión
      operationId: cerrarSesion
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Sesión cerrada exitosamente.
  /user/delete-account:
    delete:
      summary: Dar de baja la cuenta
      operationId: darBajaCuenta
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cuenta eliminada correctamente.
  /appointments/available:
    get:
      summary: Consultar disponibilidad de turnos
      operationId: obtenerTurnosDisponibles
      parameters:
        - name: especialidad
          in: query
          schema:
            type: string
        - name: medicoId
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Lista de turnos disponibles.
  /appointments/reservation:
    post:
      summary: Reservar un turno
      operationId: reservarTurno
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationAppointment'
      responses:
        '201':
          description: Turno reservado exitosamente.
  /appointments/cancel:
    delete:
      summary: Cancelar un turno
      operationId: cancelarTurno
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelationAppointment'
      responses:
        '200':
          description: Turno cancelado correctamente.
  /notifications/reminder:
    post:
      summary: Enviar recordatorio de turno
      operationId: enviarRecordatorioTurno
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Notificación enviada correctamente.
  /doctors:
    get:
      summary: Obtener listado de médicos disponibles
      operationId: obtenerMedicos
      parameters:
        - name: especialidad
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Lista de médicos.
  /studies/results:
    get:
      summary: Obtener imágenes de resultados de estudios
      operationId: obtenerResultadosEstudios
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de imágenes de estudios.
components:
  schemas:
    UserRegister:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
        dni:
          type: integer
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UserProfile:
      type: object
      properties:
        name:
          type: string
        dni:
          type: integer
        insuranceCompany:
          type: string
        afiliateNumber:
          type: integer
    Insurance:
      type: object
      properties:
        insuranceCompany:
          type: string
        afiliateNumber:
          type: integer
    ReservationAppointment:
      type: object
      properties:
        dniUser:
          type: integer
        dniDoctor:
          type: integer
        date:
          type: string
          format: date-time
    CancelationAppointment:
      type: object
      properties:
        appointmentId:
          type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
